<br /><br />


<div id="errorApp">
	<div id="topInfo">
	<div id="view-content">
		<p>View script for controller <b>Display</b> and script/action name <b>index</b></p>
		<div><?php echo $this->form; ?></div>
	</div>
	<div id="errorList">
		<table class="table table-striped table-bordered" id="errorListTable">
		</table>
		<div class="pageNav">
			<span><a href="javascript:prevPage()"><i class="icon-step-backward"></i>Prev</a></span>&nbsp;
			<span><a href="javascript:nextPage()">Next<i class="icon-step-forward"></i></a></span>
		</div>
	</div>
	</div>
	<div id="errorDetails"></div>
</div>

<script type="text/template" id="errorDetailsTemplate">
<% if(displayDetails) { %>
<div class="errorDetails">
	<div class="table">
		<div><span>Log Type</span><span><%= logType %></span></div>
		<div><span>Project</span><span><%= projectName %></span></div>
		<div><span>Environment</span><span><%= environment %></span></div>
		<div><span>Priority</span><span><%= priority %></span></div>
		<div><span>Error Number</span><span><%= errorNumber %></span></div>
		<div><span>Message</span><div class="boxMe"><blockquote><%= message %></blockquote></div></div>
		<div><span>File</span><span><%= file %></span></div>
		<div><span>Context</span><span><%= context %></span></div>
		<div><span>Stack Trace</span><div class="stackTraceDetails"><blockquote><%= stacktraceHtml %></blockquote></div></div>
		<div><span>Timestamp</span><span><%= timestamp %></span></div>
		<div><span>Priority</span><span><%= priorityName %></span></div>
	</div>
</div>
<% } %>
</script>

<script type="text/template" id="errorLineTemplate">
	<td class="errorLineShort">Not again!!</td><td class="errorLineMessage"><%= message %></td>
</script>

<script type="text/template" id="stackTraceLineTemplate">
	<div class="stackTraceLine">
		<div><%= file %></div>
		<div><span>Line:</span><span><%= line %> in <%= errClass %><%= type %><%= errFunction %></div>
	</div>
</script>
