<br /><br />


<div id="errorApp row">
	<div id="topInfo">
	<div id="view-content" class="span2">
		<div><?php echo $this->form; ?></div>
	</div>
	<div id="errorList" class="span8">
		<table class="table table-striped table-bordered" id="errorListTable">
		</table>
		<div class="pageNav">
			<span><a href="javascript:prevPage()"><i class="icon-step-backward"></i>Prev</a></span>&nbsp;
			<span><a href="javascript:nextPage()">Next<i class="icon-step-forward"></i></a></span>
		</div>
	</div>
	</div>
	<div id="errorDetails" class="row"></div>
</div>

<script type="text/template" id="errorDetailsTemplate">
<% if(displayDetails) { %>
<div class="errorDetails">
	<div class="backLink span1"><i class="icon-chevron-left backIcon"></i>Back</div>
	<div class="span9">
		<div><span class="detailsLabel">Log Type</span><span class="detailsData"><%= logType %></span></div>
		<div><span class="detailsLabel">Project</span><span class="detailsData"><%= projectName %></span></div>
		<div><span class="detailsLabel">Environment</span><span class="detailsData"><%= environment %></span></div>
		<div><span class="detailsLabel">Priority</span><span class="detailsData"><%= priority %></span></div>
		<div><span class="detailsLabel">Error Number</span><span class="detailsData"><%= errorNumber %></span></div>
		<div><span class="detailsLabel">Message</span><div class="boxMe"><blockquote><%= message %></blockquote></div></div>
		<div><span class="detailsLabel">File</span><span class="detailsData"><%= file %></span></div>
		<div><span class="detailsLabel">Context</span><span class="detailsData"><%= context %></span></div>
		<div><span class="detailsLabel">Stack Trace</span><div class="stackTraceDetails"><blockquote><%= stacktraceHtml %></blockquote></div></div>
		<div><span class="detailsLabel">Timestamp</span><span class="detailsData"><%= timestamp %></span></div>
		<div><span class="detailsLabel">Priority</span><span class="detailsData"><%= priorityName %></span></div>
	</div>
</div>
<% } %>
</script>

<script type="text/template" id="errorLineTemplate">
	<td class="errorLineShort"><%= timestamp %></td><td class="errorLineMessage"><%= message %></td>
</script>

<script type="text/template" id="stackTraceLineTemplate">
	<div class="stackTraceLine">
		<div><%= file %></div>
		<div><span>Line:</span><span><%= line %> in <%= errClass %><%= type %><%= errFunction %></div>
	</div>
</script>
